<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1(current)</name>
   <tag></tag>
   <elementGuidId>a6ae5dcb-8d6d-4da0-bc3a-30369c334299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.page-item.active > span.page-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[3]/div[3]/div/div[2]/ul/li[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12444c12-e045-4d7e-ad28-cd64c4c62688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>6ca8afdc-963c-48f1-bca6-84d02a461892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1(current)</value>
      <webElementGuid>4612dd30-b53d-4b7f-b4ee-cbcb0f6e0ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;vh-100 m-0 container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;px-0 pb-5 col-lg-10 offset-lg-2&quot;]/div[@class=&quot;bg-white rounded p-5 mt-5 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;justify-content-end row&quot;]/div[@class=&quot;col-auto&quot;]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item active&quot;]/span[@class=&quot;page-link&quot;]</value>
      <webElementGuid>1cf413c8-4364-4272-923f-45fc6d9aa0b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div[3]/div/div[2]/ul/li[2]/span</value>
      <webElementGuid>ef4b22c1-0d78-486f-b2ba-a23c255a61e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::span[1]</value>
      <webElementGuid>e78b947a-6ec8-4db6-abdc-020e41af2785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAVA, FUNDAMENTAL, INPUT'])[1]/following::span[4]</value>
      <webElementGuid>8357dfd8-e203-439a-865e-ce866509e40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::span[3]</value>
      <webElementGuid>d57b5e58-a939-4da8-aced-76e1975bb345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>79e60534-0b22-4b10-9870-f7b9aef54b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1(current)' or . = '1(current)')]</value>
      <webElementGuid>a4b46904-910d-444a-93fe-3ebcb192dc7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
