<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SuccessTopik berhasil dihapus</name>
   <tag></tag>
   <elementGuidId>7413168b-0dd7-4680-868e-3d2e22d84b99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fade.position-fixed.bottom-0.end-0.success-alert.d-flex.align-items-center.alert.alert-success.alert-dismissible.show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69189326-1b46-4a8c-8be4-0de148477701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>dc4eb721-23b3-4eeb-9b96-58d8881569e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fade position-fixed bottom-0 end-0 success-alert d-flex align-items-center alert alert-success alert-dismissible show</value>
      <webElementGuid>d6cde439-5b0e-4bec-9f93-f8eedb8f2a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Success!Topik berhasil dihapus</value>
      <webElementGuid>f1ae0ea4-d77f-4294-a886-6f35694e2c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fade position-fixed bottom-0 end-0 success-alert d-flex align-items-center alert alert-success alert-dismissible show&quot;]</value>
      <webElementGuid>41330bbb-f9f4-4ab9-93ab-67b983f4b1a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>267a4533-218b-423f-a127-e1758a7191b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>c71f4465-b666-4a38-b512-b21d5255b5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Success!Topik berhasil dihapus' or . = 'Success!Topik berhasil dihapus')]</value>
      <webElementGuid>506ba6e9-ba18-4276-853a-c620f15deb4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
