<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload</name>
   <tag></tag>
   <elementGuidId>fc6f98df-e1c3-4559-9f9d-c7a2188a31d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.rounded.w-100.btn.btn-primary.form-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3a38f13f-e771-4793-bd3f-eafaea8afeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded w-100 btn btn-primary form-label</value>
      <webElementGuid>7a6119b4-ae98-433b-a1b0-f2e541abc84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>thumbnail-field</value>
      <webElementGuid>8cae4003-face-476d-8ac1-ba60243987a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b03f9b9-f046-4427-9224-b6a07233c4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5694dcd4-463c-42cb-90ed-e5aeb6f46574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>214cc92e-b345-497d-a64b-005f011c6893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog modal-xl modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;mx-0 mb-3 row&quot;]/div[@class=&quot;col-6 col&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-3 pe-0 col&quot;]/label[@class=&quot;rounded w-100 btn btn-primary form-label&quot;]</value>
      <webElementGuid>00464c08-eeab-40d6-885c-9d39b226e7a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::label[1]</value>
      <webElementGuid>c751ff6d-a901-44f5-9a64-d10730947052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih file untuk diupload'])[1]/preceding::label[1]</value>
      <webElementGuid>f0682a9a-7410-4cd1-b82e-4b764da75527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>982ae1a2-976a-4d95-8298-2abeb6639f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/label</value>
      <webElementGuid>b2ae9243-970e-42a4-a455-2b5b56ef2bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>f8bd9e96-a660-4a65-958d-0ed894dc8c92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
