<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Praktik</name>
   <tag></tag>
   <elementGuidId>0caa8fef-cc82-43c0-95a5-60d8eb7753f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/nav/div/div[6]/div/div/div[5]/a/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1782f497-5c97-4e56-8590-1b0dbbd9ab0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Praktik</value>
      <webElementGuid>576e917c-63e1-4277-9bad-286857f7c754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;vh-100 m-0 container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;p-0 position-fixed col-lg-2&quot;]/nav[@class=&quot;flex-column bg-white vh-100 navbar navbar-expand navbar-light&quot;]/div[@class=&quot;flex-column w-100 fsz-1125 accordion navbar-nav nav-pills&quot;]/div[@class=&quot;w-100 accordion-item-nav accordion-item nav-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body-nav p-0 accordion-body&quot;]/div[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link ps-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-auto&quot;]/span[1]</value>
      <webElementGuid>03ca1bd0-0fb9-4c69-9c6f-0c1c4e3606f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div[6]/div/div/div[5]/a/div/div/span</value>
      <webElementGuid>82b752ef-001e-4c33-8d3d-0ee2f5179647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek Kemampuan'])[1]/following::span[1]</value>
      <webElementGuid>17961600-872b-4063-aa65-d9cddde4b137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuis Bab'])[1]/following::span[2]</value>
      <webElementGuid>f5f3902c-c96e-4e0d-8c99-32ff94c40eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan'])[1]/preceding::span[1]</value>
      <webElementGuid>8b925f9c-9d79-49e2-95cb-ec8ae8e55416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belajar'])[1]/preceding::span[2]</value>
      <webElementGuid>c0ca6864-7375-4107-916e-72070275f370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Praktik']/parent::*</value>
      <webElementGuid>cb3c34bd-fab0-449f-8735-9ad002fd7b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[5]/a/div/div/span</value>
      <webElementGuid>ed8877b9-2178-429b-978b-eec7f30299a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Praktik' or . = 'Praktik')]</value>
      <webElementGuid>f82ed946-5c81-4361-8097-065fa6eb501c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
